// Data models (profiles and settings) persisted by the plugin through Obsidian's
// loadData()/saveData() (written to data.json).

import { Lang } from "./i18n";

// Terminal kind: local (PTY via node-pty, or the line-editing fallback) or
// remote (SSH via ssh2).
export type TerminalKind = "local" | "ssh";

// xterm.js cursor style.
export type CursorStyle = "block" | "underline" | "bar";

// Default SSH port, applied wherever a profile does not specify one.
export const DEFAULT_SSH_PORT = 22;

// Fields common to any terminal profile.
export interface BaseProfile {
	id: string; // unique id (generated by generateId())
	name: string; // user-visible name
	kind: TerminalKind; // "local" | "ssh"
	favorite: boolean; // when true, shown at the top of the picker
	// Optional command run automatically on open (e.g. "claude").
	startupCommand?: string;
}

// LOCAL terminal profile (a shell on this machine; WSL on Windows by default).
export interface LocalProfile extends BaseProfile {
	kind: "local";
	// Shell or full command line. Empty/undefined => automatic detection
	// (WSL/pwsh/cmd on Windows, or $SHELL on Linux/macOS). May include arguments,
	// e.g. "pwsh.exe -c wsl.exe"; it is tokenized (quotes honored) before spawn.
	shell?: string;
	// Extra arguments appended after the command above (e.g. ["-d", "Ubuntu"]).
	args?: string[];
	// Working directory. Empty => vault root.
	cwd?: string;
}

// REMOTE terminal profile over SSH.
export interface SshProfile extends BaseProfile {
	kind: "ssh";
	host: string;
	port: number; // defaults to DEFAULT_SSH_PORT when missing
	username: string;
	// Authentication: by password and/or by private key (either one works).
	password?: string;
	privateKeyPath?: string; // key file path (PEM/OpenSSH)
	passphrase?: string; // key passphrase, if any
	// Initial remote directory used by the file browser (SFTP).
	remoteHome?: string;
}

// Discriminated union on "kind": narrow with if (p.kind === ...).
export type TerminalProfile = LocalProfile | SshProfile;

// Global plugin settings.
export interface FzSettings {
	fontFamily: string;
	fontSize: number;
	cursorStyle: CursorStyle;
	cursorBlink: boolean;
	scrollback: number;
	// Interface language (English by default, Portuguese-Brazil optional).
	language: Lang;
	// Default local shell on Windows when a profile does not define one.
	// "wsl" opens the WSL bash; "pwsh"/"powershell"/"cmd" or a full command line
	// are also accepted.
	defaultWindowsShell: string;
	// Command used by the "Open Claude Code" action.
	claudeCommand: string;
	// User-managed profiles (local and SSH).
	profiles: TerminalProfile[];
}

// Defaults applied on first run (and as a merge fallback).
export const DEFAULT_SETTINGS: FzSettings = {
	fontFamily:
		"'JetBrainsMono Nerd Font', 'Cascadia Code', Menlo, Consolas, 'Courier New', monospace",
	fontSize: 14,
	cursorStyle: "block",
	cursorBlink: true,
	scrollback: 5000,
	language: "en",
	defaultWindowsShell: "wsl",
	claudeCommand: "claude",
	profiles: [],
};
